version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always

  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: always
