version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:5000

    ports:
      - '3000:3000'
    restart: always

  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      PORT: 5000
      PATH_TO_CITY_JSON: ./data/cities.json
    ports:
      - '5000:5000'
    restart: always
